apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: {{.GetC "frontend/svc/balancer" }}
  ports:
    # the port that this service should serve on
    - port: {{.GetC "frontend/svc/port" }}
  selector:
    name: frontend
