apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: {{.Get "redis-master/rc/number" }}
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      containers:
      - name: {{.Get "redis-master/rc/container/name" }}
        image: {{.Get "redis-master/rc/container/image" }}:{{.Get "redis-master/rc/container/version" }}
        ports:
        - containerPort: {{.Get "redis-master/rc/container/port" }}
