{{ $number_of_replicas    := getNumber "rc/redis-slave/number" }}
{{ $container_name        := getString "rc/redis-slave/name" }}
{{ $container_image       := getString "rc/redis-slave/image" }}
{{ $container_version     := getString "rc/redis-slave/version" }}
{{ $container_port        := getNumber "rc/redis-slave/port" }}

apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-slave
  labels:
    name: redis-slave
spec:
  replicas: {{ $number_of_replicas }}
  selector:
    name: redis-slave
  template:
    metadata:
      labels:
        name: redis-slave
    spec:
      containers:
      - name: {{ $container_name }}
        image: {{ $container_image }}:{{ $container_version }}
        ports:
        - containerPort: {{ $container_port }}
